socialnet/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import *
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage),
    path('contacts/', contacts),
    path('about_us/', about_us),
    path('posts/<int:id>/', post_detail),
    path('posts-list-cbv/', PostListView.as_view(), name='posts-list-cbv'),
    path('posts-list-filter/', PostListFilterView.as_view(), name='posts-list-filter'),
    path('posts-api/', PostFromApi.as_view(), name='posts-api'),
    path('posts-api/<int:id>/', PostDetailFromApi.as_view(), name='post-api'),
    path('todo-api-list/', TodoFromApi.as_view(), name='todo-api'),
    path('todo-detail-api/<int:id>/', TodoDetailFromApi.as_view(), name='todo-api'),
    path('posts-cbv/<int:id>/', PostDetailView.as_view(), name='post-detail-cbv'),
    path('profile/<int:id>/', profile_detail, name='profile'),
    path('category_info/', category_list),
    path('category_info/<int:id>/', category_detail),
    path('short_video-cvb/<int:pk>/', Short_videoView.as_view(), name='short-info-cvb'),
    path('short-lst-cvb/', Short_listView.as_view(), name='shorts-list-cvb'),
    path('shorts-filter/', ShortsFilterView.as_view(), name='shorts-filter'),
    path('saved_post_list/', saved_post_list, name='saved_post_list'),
    path('update-short/<int:id>/', update_short, name='update-short'),
    path('<int:user_id>/', user_post, name='user_posts'),
    path('posts/', post_list, name='posts'),
    path('add-post/', create_post, name='add-post'),
    path('update-post/<int:id>/', update_post, name='update-post'),
    path('delete-post/<int:id>/', delete_post, name='delete-post'),
    path('add-post-form/', add_post_form, name='add-post-form'),
    path('edit-comment/<int:id>/', edit_comment, name='edit-comment'),
    path('delete-comment/<int:id>/', delete_comment, name='delete-comment'),
    path('add-short/', add_short, name='add-short'),
    path('add-saved/', add_saved, name='add-saved'),
    path('remove-saved/', remove_saved, name='remove-saved'),
    path('registration/', register, name='register'),
    path('users/', include('userapp.urls')),
    path('search-cvb/', SearchView.as_view(), name='search-cvb'),
    path('search-result-cvb/', Search_resultView.as_view, name='search-result-cvb'),
    path('add-subscriber/<int:profile_id>/', add_subscriber, name='add-subscriber'),
    path('subcsribes/<int:profile_id>/', SubcsribesView.as_view(), name='subcsribes'),
    path('remove-follower/<int:profile_id>/', remove_follower, name='remove-follower'),
    path('note_lst/', show_notification, name='note_lst'),
    path('note_lst_cvb/', Show_notificationView.as_view(), name='note_lst_cvb'),
    path('add-profile/', add_profile, name='add-profile'),
    path('edit-profile/<int:id>/', edit_profile, name='edit-profile'),
    path('about/', AboutView.as_view(), name='about'),
    path('contactsus/', ContactsusView.as_view(), name='contactsus'),
    path('faq/', FAQView.as_view(), name='faq'),
    path('stuff/', StuffView.as_view(), name='stuff'),





]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userapp/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    # path('registration/', register, name='register'),
    path('sign-in/', sign_in, name='sign-in'),
    path('sign-out/', sign_out, name='sign-out'),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(to=User, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=55)
    description = models.TextField(null=True, blank=True)
    subscriber = models.ManyToManyField(to=User, related_name='followed_user', blank=True)
    photo = models.ImageField(upload_to='profile_photo/', null=True)
    link_fb = models.CharField(max_length=255, null=True, blank=True)
    photo = models.ImageField(
        upload_to='profile_photo/',
        null=True
    )
    link_fb = models.CharField(
        max_length=255, null=True, blank=True
    )
    whatsapp = models.CharField(
        max_length=30, null=True, blank=True
    )
    telegram = models.CharField(
        max_length=55, null=True, blank=True
    )

class Post(models.Model):
    STATUS_CHOICES = (
        ('Posted', 'Posted'),
        ('Unposted', 'Unposted')
    )

    name = models.CharField('Header', max_length=80, null=True, blank=True)
    description = models.TextField('Description', null=True, blank=True)
    photo = models.ImageField('Photo', null=True, blank=False, upload_to='post_images/')
    status = models.CharField('Status', max_length=200, choices=STATUS_CHOICES, default="Posted")
    creator = models.ForeignKey(
        to=User,
        on_delete=models.SET_NULL,
        null=True,
        blank=False,
        verbose_name="Post author",
        related_name='posts'
    )
    category = models.ManyToManyField(
        to='Category', blank=True, verbose_name='Categories',
    )
    likes = models.PositiveIntegerField('Likes', default=0)


    def __str__(self):
        return f'{self.name} - {self.status}'


class Category(models.Model):
    RATING_CHOICES = (
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
        (6, 6),
        (7, 7),
        (8, 8),
        (9, 9),
        (10, 10)
    )

    name = models.CharField(max_length=50)
    rating = models.PositiveSmallIntegerField(choices=RATING_CHOICES, null=True, blank=True)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return f'{self.name} - {self.rating}'


class Comment(models.Model):
    post = models.ForeignKey(
        to=Post,
        on_delete=models.CASCADE,
    )
    created_by = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        null=True, blank=False
    )
    comment_text = models.TextField()
    likes_qty = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'
        ordering = ['created_at']

    def __str__(self):
        return self.comment_text[:20]


class Short(models.Model):
    user = models.ForeignKey(User, verbose_name='Posted by', on_delete=models.CASCADE)
    video = models.FileField('Video', null=True, blank=False, upload_to='post_videos/')
    created_at = models.DateTimeField('Upload data', auto_now_add=True)
    views_qty = models.PositiveIntegerField('Views', default=0)
    viewed_users = models.ManyToManyField(
        to=User,
        blank=True,
        related_name='viewed_shorts'
    )
    description = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        verbose_name = 'Video'
        verbose_name_plural = 'Videos'

    def __str__(self):
        return f'{self.video} - {self.created_at}'


class SavedPosts(models.Model):
    user = models.OneToOneField(User, verbose_name='User', on_delete=models.CASCADE)
    post = models.ManyToManyField(Post,
                                  verbose_name='Saved post',
                                  related_name='saved_posts')



    class Meta:
        verbose_name = 'Saved Post'
        verbose_name_plural = 'Saved Posts'

    def __str__(self):
        return f'{self.user} - {self.post}'

class Notification(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.PROTECT)
    text = models.CharField(max_length=255)
    is_showed = models.BooleanField(default=False)

    def __str__(self):
        return self.text

core/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib import messages
from django.views.generic import ListView, DetailView
from django_filters.views import FilterView
from django.views import View
from .models import *
from .forms import *
from .filters import *
import requests


# Create your views here.
class NoContextView(View):
    template_name = None
    def get(self, request):
        return render(request, self.template_name)
class AboutView(NoContextView):
    template_name = 'about.html'

class FAQView(NoContextView):
    template_name = 'faq.html'

class StuffView(NoContextView):
    template_name = 'stuff.html'

class ContactsusView(NoContextView):
    template_name = 'contactsus.html'


def homepage(request):
    context = {}
    posts_list = Post.objects.all()
    context['posts'] = posts_list
    short_list = Short.objects.all()
    context['shorts'] = short_list
    return render(request, 'home.html', context)


def post_detail(request, id):
    context = {}
    post_object = Post.objects.get(id=id)
    context['post'] = post_object
    comment_form = CommentForm()
    context['comment_form'] = comment_form
    comments_list = Comment.objects.filter(post=post_object)
    context['comments'] = comments_list
    if request.method == "GET":
        return render(request, 'post_info.html', context)
    elif request.method == 'POST':
        if 'like' in request.POST:
            post_object.likes += 1
            post_object.save()
            Notification.objects.create(
                user=post_object.creator,
                text=f'{request.user.username} likes your post {post_object.id}'
            )
        elif 'dislike' in request.POST:
            post_object.likes -= 1
            post_object.save()
            Notification.objects.create(
                user=post_object.creator,
                text=f'{request.user.username} dislikes your post {post_object.id}'
            )
            return redirect(post_detail, id=id)
        else:
            comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
           new_comment = comment_form.save(commit=False)
           new_comment.created_by = request.user
           new_comment.post = post_object
           new_comment.save()
           Notification.objects.create(
               user=post_object.creator,
               text=f'{request.user.username} Commented your post {post_object.id}'
           )
        return redirect(post_detail, id=id)

class PostDetailView(View):
    def get_context(self):
        id = self.kwargs['id']
        context = {}
        post_object = Post.objects.get(id=id)
        context['post'] = post_object
        comment_form = CommentForm()
        context['comment_form'] = comment_form
        comments_list = Comment.objects.filter(post=post_object)
        context['comments'] = comments_list
        return context


    def get(self, request, *args, **kwargs):
        context = self.get_context()
        return render(request, 'post_info.html', context)

    def post(self, request, *args, **kwargs):
        context = context = self.get_context()
        post_object = context['post']
        if 'like' in request.POST:
            post_object.likes += 1
            post_object.save()
            Notification.objects.create(
                user=post_object.creator,
                text=f'{request.user.username} likes your post {post_object.id}'
            )
        elif 'dislike' in request.POST:
            post_object.likes -= 1
            post_object.save()
            Notification.objects.create(
                user=post_object.creator,
                text=f'{request.user.username} dislikes your post {post_object.id}'
            )
        else:
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                new_comment = comment_form.save(commit=False)
                new_comment.created_by = request.user
                new_comment.post = post_object
                new_comment.save()
                Notification.objects.create(
                    user=post_object.creator,
                    text=f'{request.user.username} Commented your post {post_object.id}'
                )
        return redirect('post-detail-cbv', id=post_object.id)


def edit_comment(request, id):
    comment = Comment.objects.get(id=id)
    if request.user != comment.created_by:
        return redirect(post_detail)
    if request.method == 'POST':
        form = CommentForm(
            data=request.POST,
            instance=comment
        )
        if form.is_valid():
            form.save()
            return redirect(post_detail, id=comment.post.id)
    form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'edit_comment.html', context)


def delete_comment(request, id):
    comment = Comment.objects.get(id=id)
    if request.user != comment.created_by:
        return redirect(post_detail)
    comment.delete()
    return redirect(post_detail, id=comment.post.id)


class SubcsribesView(View):
    def get(self, request, *args, **kwargs):
        user_object = User.objects.get(id=kwargs['user_id'])
        profiles_list = user_object.followed_user_profile.all()
        context = {'profiles_list': profiles_list}
        return render(request, 'subscribes.html', context)


def add_profile(request):
    profile_form = ProfileForm()
    context = {'profile_form': profile_form}
    if request.method == 'POST':
        profile_form = ProfileForm(request.POST, request.FILES)
        if profile_form.is_valid():
            profile_object = profile_form.save(commit=False)
            profile_object.user = request.user
            profile_object.save()
            return redirect(profile_detail, id=profile_object.id)
        else:
            return HttpResponse('Not valid')
    return render(request, 'add_profile.html', context)


def edit_profile(request, id):
    profile = Profile.objects.get(id=id)
    profile_form = ProfileForm(
        instance=profile
    )
    context = {'profile_form': profile_form}
    if request.method == 'POST':
        profile_form = ProfileForm(instance=profile, data=request.POST, files=request.FILES)
        if profile_form.is_valid():
            profile_form.save()
            return redirect(profile_detail, id=profile.id)
    return render(request, 'update_profile.html', context)




def add_saved(request):
    if request.method == "POST":
        post_id = request.POST['post_id']
        post_object = Post.objects.get(id=post_id)
        saved_post, created = SavedPosts.objects.get_or_create(user=request.user)
        saved_post.post.add(post_object)
        saved_post.save()
        return redirect('/saved_post_list/')

def remove_saved(request):
    if request.method == "POST":
        post_id = request.POST['post_id']
        post_object = Post.objects.get(id=post_id)
        saved_post = SavedPosts.objects.get(user=request.user)
        saved_post.post.remove(post_object)
        saved_post.save()
        return redirect('/saved_post_list/')

def add_subscriber(request, profile_id):
    profile = Profile.objects.get(id=profile_id)
    profile.subscriber.add(request.user)
    profile.save()
    messages.success(request, 'You are one of us')
    new_notification = Notification(
        user = profile.user,
        text = f'user {request.user.username} follow you'
    )
    new_notification.save()
    return redirect(f'/profile/{profile.id}/')

def remove_follower(request, profile_id):
    profile = Profile.objects.get(id=profile_id)
    profile.subscriber.remove(profile_id)
    profile.save()
    messages.success(request, 'You are not follower')
    return redirect(f'/profile/{profile.id}')


def post_list(request):
    context = {}
    post_list = Post.objects.all()
    context['posts'] = post_list
    return render(request, 'post_lst.html', context)

class PostListView(ListView):
    queryset = Post.objects.all()
    template_name = 'posts-list-cbv.html'

class PostListFilterView(FilterView):
    model = Post
    filterset_class = PostFilters
    filterset_fields = ['id', 'creator', 'likes']
    template_name = 'short-filter.html'




def saved_post_list(request):
    posts = Post.objects.filter(saved_posts__user=request.user)
    context = {'posts': posts}
    return render(request, 'saved_post_list.html', context)

def  update_post(request, id):
    context = {}
    post_object = Post.objects.get(id=id)
    if request.user != post_object.creator:
        return HttpResponse ('No access')
    if request.method == 'POST':
        post_form = PostForm(
            data=request.POST,
            files=request.FILES,
            instance=post_object
        )
        if post_form.is_valid():
            post_form.save()
            return redirect(post_detail, id=post_object.id)
        else:
            messages.warning(request, 'Form is not valid')
            return render(request, 'update_post.html', context)
    post_form = PostForm(instance=post_object)
    context['post_form'] = post_form
    return render(request, 'update_post.html', context)

def delete_post(request, id):
    post = Post.objects.get(id=id)
    if request.user != post.creator:
        return HttpResponse ('No access')
    post.delete()
    return redirect(homepage)


def profile_detail(request, id):
    context = {}
    profile = Profile.objects.get(id=id)
    context['profile'] = profile
    user_posts = Post.objects.filter(creator=profile.user)
    context['user_posts'] = user_posts
    return render(request, 'profile_detail.html', context)


def user_post(request, user_id):
    user = User.objects.get(id=user_id)
    posts = Post.objects.filter(creator=user)
    context = {
        'user': user,
        'posts': posts
    }
    return render(request, 'user_posts.html', context)

core/templates/about.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}

<div><h2 class="container p-2 my-5 bg-dark text-white">About us</h2></div>

<div><center>
Detail-oriented Civil Engineer and PE with 5 years of experience and a zest for solving complex problems.
    <br>
Seeking to use proven project management and design skills to improve quality, cost and time metrics for NEP Engineering.
</center></div>


{% endblock %}

core/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    {% load django_bootstrap5 %}
    <meta charset="UTF-8">
    <title>SocialNet</title>

<html>
    <head>
        {% bootstrap_css %}
        {% bootstrap_javascript %}
        <link rel="stylesheet" href="{% static 'main.css' %}">
    </head>
    <body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
            <div class="container-fluid">
              <a class="navbar-brand" href="/"><img src="{% static 'Instagram_logo_2016.svg.png' %}" height="40px"></a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="mynavbar">
                <ul class="navbar-nav me-auto">
                  <li class="nav-item">
                    <a class="nav-link my-focus" href="/">MAIN</a>
                  </li>
                     {% if request.user.profile %}
                  <li class="nav-item">
                    <a class="nav-link my-focus" href="{% url 'profile' request.user.profile.id %}">Profile</a>
                  </li>
                    {% else %}
                    <li>
                    <div>
                    <a class="nav-link my-focus" href="{% url 'add-profile' %}"> Add profile </a>
                    </div>
                    {% endif %}
                    </li>
                    <li class="nav-item">
                    <a class="nav-link my-focus" href="{% url 'note_lst' %}">Notification -
                        {{ request.user.notification_set.count }}</a>
                    </li>
                  <li class="nav-item">
                    <a class="nav-link my-focus" href="{% url 'shorts-list-cvb' %}">Reels</a>
                  </li>
                     <li class="nav-item">
                    <a class="nav-link my-focus" href="{% url 'shorts-filter' %}">Reels+</a>
                  </li>
                    <li class="nav-item">
                    <a class="nav-link my-focus" href="{% url 'add-short' %}">Add Reel</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link my-focus" href="{% url 'posts' %}">Posts</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link my-focus" href="{% url 'posts-list-filter' %}">Posts+</a>
                  </li>
                    <li class="nav-item">
                    <a class="nav-link my-focus" href="{% url 'posts-api' %}">PostsAPI</a>
                  </li>
                     <li class="nav-item">
                    <a class="nav-link my-focus" href="{% url 'todo-api' %}">To do API</a>
                  </li>
                    {% if request.user.is_authenticated %}
                    <div> <a class="nav-link my-focus"  href="{% url 'add-post-form' %}"> Add post(dj form) </a>
                  </li>">
                    </div>
                  <li class="nav-item">
                    <a class="nav-link my-focus" href="{% url 'saved_post_list' %}">SavedPosts</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link my-focus" href="{% url 'add-post' %}">Addpost</a>
                  </li>
                    {% endif %}
                    <li class="nav-item">
                    <a class="nav-link my-focus" href="{% url 'about' %}">About</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link my-focus" href="{% url 'contactsus' %}">Contacts</a>
                  </li>
                    <li class="nav-item">
                    <a class="nav-link my-focus" href="{% url 'faq' %}">FAQ</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link my-focus" href="{% url 'stuff' %}">Stuff</a>
                  </li>
                    <li class="nav-item">
                    <a class="nav-link my-focus" href="{% url 'posts-list-cbv' %}">POSTS</a>
                  </li>
                    <li class="nav-item">
                    <a class="nav-link my-focus" href="{% url 'sign-in' %}">Sign in</a>
                  </li>
                    <li class="nav-item">
                    <a class="nav-link my-focus" href="{% url 'sign-out' %}">Sign out</a>
                  </li>
                </ul>

                <form class="d-flex">
                  <input class="form-control me-2" type="text" placeholder="Search">
                    <a href="{% url 'search-cvb' %}">
                        <button class="btn btn-secondary" type="button">Search</button>
                    </a>
                </form>
              </div>
            </div>
        </nav>
    <div class="row">
        <div class="col-2">
            <div class="my-focus"><center>
                {% if request.user.is.authenticated %}
                HI, {{ request.user.username }}
                {% else %}
                Please sign in
                {% endif %}</center>
            </div>
            <div class="my-focus"><center>MAIN</center></div>
            <div class="my-focus"><center>
                <a href="{% 'search-cvb' %)"> </a>SEARCH</center></div>
            <div class="my-focus"><center>POPULAR</center></div>

        </div>
    <div class="col-10">
        {% if messages %}
        <div class="col-9">
            {% for message in messages %}
            <div
                {% if message.tags %}
                 class="alert alert-{{ message.tags }}"
                {% endif %}>
                {{ message }}
            </div>
            {% endfor %}
        </div>
        {% endif %}

         {% block content %}

         {% endblock %}
    </div>

    </body>
</html>

core/templates/home.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
    <div class="row">
    {% for short in shorts %}
        <div class="col">
            <a href="{% url 'short-info-cvb' short.id %}">
                <div>
                    <video
                        class="custom-circle"
                        width="100px" src="{{ short.video.url}}">
                    </video>
                </div>
            </a>
        </div>
    {% endfor %}
    </div>
<hr>

    <h1 class="alert alert-dark">
        <strong><center>Hello World! This is socialnet!</center></strong> </h1>
    <div>
        <h1><span class="badge bg-secondary"> Start page </span></h1>
    </div>
    <div>
        <a href="/registration/"><button type="submit" class="btn btn-secondary">Sign up</button></a>
    </div>
    <h3>Hello user, {{ name }}</h3>
    <div>
        <a href="/profile/{{request.user.profile.id}}">
            PROFILE {{ request.user.username}}
        </a>
    </div>
    <div> {{ request.user }} </div>
    <h4> POSTS </h4>
    <ol>
    {% for post in posts %}
        <div>
            <a href="{% url 'user_posts' post.creator.id %}">
            </a>
        </div>
        <li>
        <div>
            <a href="/posts/{{ post.id }}">
            {{post.name}}</a>

        </div>
        </li>
    {% endfor %}
    </ol>
    <h2> CATEGORIES </h2>
        <div>
            <a href="/category_info/">CATEGORY</a>
        </div>
    <h4> SHORTS </h4>
        <div>
            <a href="{% url 'shorts-list-cvb' %}">Shorts</a>
        </div>

{% endblock %}

core/templates/post_lst.html
{% extends 'base.html' %}
{% block content %}
{% for post in posts %}

<div class="post">

  <div> <h2 class="container p-2 my-5 bg-dark text-white"> POST </h2></div>

        <div class="post col-lg-4 col-md-6">
            <a href="/posts/{{ post.id }}">
                {{ post.name }}
            </a>

        </div>

<div><a href="{% url 'profile' post.creator.profile.id %}"> AUTHOR {{ post.creator }}</a></div>

</div>
            {% if post.photo %}
                <div>
                    <img src="{{ post.photo.url}}" height="200px">
                </div>
            {% endif %}


{% endfor %}


{% endblock %}

core/templates/posts-list-filter.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}

    {% include 'includes/search_form.html' %}

      {% for post in filter.qs %}
       <div class="post">
           <div> <h2 class="container p-2 my-5 bg-dark text-white"> POST </h2></div>
                <div class="post col-lg-4 col-md-6">
                    <a href="/posts/{{ post.id }}">
                        {{ post.name }}
                    </a>
                </div>
             <div><a href="{% url 'profile' post.creator.profile.id %}"> AUTHOR {{ post.creator }}</a>
             </div>
       </div>
    {% if post.photo %}
        <div>
            <img src="{{ post.photo.url}}" height="200px">
        </div>
    {% endif %}
    <hr>
      <form method="get">
        {% bootstrap_form filter.form  %}
        <button class="btn btn-info">Apply</button>
      </form>
    <hr>

    {% endfor %}


{% endblock %}

core/templates/saved_post_list.html
{% extends 'base.html' %}
{% block content %}

  <div> <h1 class="container p-1 my-2 bg-dark text-white">SAVED POSTS</h1></div>

  {% for post in posts %}
  <div class="post"> </div>
    <div>
      <a href="/posts/{{ post.id }}">
        {{ post.name }} </a>
        {% if post.photo %}
          <div>
            <img src="{{ post.photo.url}}" height="200px">
          </div>
        {% endif %}
    </div>
{% endfor %}

{% endblock %}

core/templates/search.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}

 {% include 'includes/search_form.html' %}

{% endblock %}

core/templates/short-filter.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  {% include 'includes/search_form.html' %}

  {% for short in filter.qs %}

  <div class="alert alert-secondary">
    <div> <h2 class="container p-1 my-2 bg-dark text-white"> SHORT {{ short.id }} </h2></div>
    <div>
      <hr>
    <a href="{% url 'short-info-cvb' short.id %}">
      <video height="240px" src="{{ short.video.url}}">
      </video>
      Short #{{ short.id }}
    </a>
    </div>
  </div>
  {% endfor %}

<hr>
  <form method="get">
    {% bootstrap_form filter.form  %}
    <button class="btn btn-info">Apply</button>
  </form>
<hr>


{% endblock %}

core/templates/short-lst-cvb.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}

{% for short in short_lst %}

<div class="alert alert-secondary">
  <div> <h2 class="container p-1 my-2 bg-dark text-white"> SHORT {{ short.id }} </h2></div>
  <div>
    <hr>
  <a href="{% url 'short-info-cvb' short.id %}">
    <video height="240px" src="{{ short.video.url}}">
    </video>
    Short #{{ short.id }}
  </a>
  </div>
</div>
{% endfor %}


{% endblock %}

core/templates/short_info-cvb.html
{% extends 'base.html' %}

{% block content %}

<div> <h1 class="container p-2 my-5 bg-dark text-white">SHORT </h1> </div>

<div class="alert alert-secondary">
    <div> <h2>Created at: {{ short.created_at }}</h2></div>

    <div> <h2>Name: {{ short.video}}</h2> </div>

    <div><h2> Uploaded by: {{ short.user}}</h2></div>

    <div> <h2>Views: {{ short.views_qty }}</h2></div>

    <div> <h2>User unique views: {{ short.viewed_users.count }}</h2></div>
</div>
<div>
    Description: {{ short.description }}
</div>
<a href="{% url 'update-short' short.id %}" class="btn btn-info"> Edit </a>
<br>
    <video width="900" height="600" controls src="{{ short.video.url }}">
      Your browser does not support the video tag.
    </video>

{% endblock %}

core/templates/update_post.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}

  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form post_form %}
    <button class="btn btn-info"> Update </button>
  </form>

{% endblock %}